version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/var/lib/postgresql/14
      - ./deployment/volumes/backups:/backups
    ports:
      - "5432:5432"

  worker:
    image: kartoza/georepo_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/tegola_config:/opt/tegola_config
      - ./volumes/layer_tiles:/opt/layer_tiles
      - ./volumes/django_cache:/home/web/django_cache

  celery_beat:
    image: kartoza/georepo_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/tegola_config:/opt/tegola_config
      - ./volumes/layer_tiles:/opt/layer_tiles
      - ./volumes/django_cache:/home/web/django_cache

  dev:
    image: kartoza/georepo_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/tegola_config:/opt/tegola_config
      - ./volumes/layer_tiles:/opt/layer_tiles
      - ./volumes/django_cache:/home/web/django_cache
