version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/var/lib/postgresql/14
      - ./deployment/volumes/backups:/backups
    ports:
      - "5432:5432"

  worker:
    image: kartoza/georepo_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    env_file: .azure.env
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/tegola_config:/opt/tegola_config
    links:
      - db
      - azurite

  celery_beat:
    image: kartoza/georepo_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    env_file: .azure.env
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/tegola_config:/opt/tegola_config

  dev:
    image: kartoza/georepo_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    env_file: .azure.env
    volumes:
      - ../:/home/web/project
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/tegola_config:/opt/tegola_config
    links:
      - db
      - worker
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    entrypoint: ["azurite", "--blobHost", "0.0.0.0", "--blobPort", "10000","-l", "data"]
    volumes:
      - ./volumes/azurite:/opt/azurite/data
    ports:
      - 10000:10000
